# Spring boot application
spring:
  application:
    name: springboot-provider
  redis:
    jedis:
      database: 0
      pool:
        max-active: 8
        max-idle: 9
        max-wait: -1
        min-idle: 0
      redis-dev:
        host:
        prot:
        password:
        testOnBorrow: false
      redis-test:
        host:
        prot:
        password:
        testOnBorrow: false
      redis-online:
        host:
        prot:
        password:
        testOnBorrow: false
    timeout: 0

server:
  port: 9090

management:
  port: 9091

# Dubbo Application
dubbo:
# Base packages to scan Dubbo Component: @com.alibaba.dubbo.config.annotation.Service
  scan:
    basePackages: com.ghost.springboot.service.impl
## The default value of dubbo.application.name is ${spring.application.name}
  application:
    id: dubbo-provider
    name: dubbo-provider
# Dubbo Protocol
  protocol:
    id: dubbo
    name: dubbo
## Random port
    port: -1
## Dubbo Registry
  registry:
    id: my-registry
    address: nacos://47.106.227.5:8848

## DemoService version
demo:
  service:
    version: 1.0.0
    name: 1.0.0