# Spring boot application
spring:
  application:
    name: springboot-consumer

server:
  port: 8080
management:
  prot: 8081

## nacos
nacos:
  config:
    server-addr: nacos address:8848
  discovery:
    server-addr: nacos address:8848

## application
dubbo:
  application:
    id: dubbo-consumer
    name: dubbo-consumer
    qos-port: 33333
## nacos registry address
  registry:
    id: my-registry
    address: nacos://nacos address:8848
  protocol:
    id: dubbo
    name: dubbo
    port: -1
#  scan:
#    basePackages: com.ghost.springboot.service
  consumer:
    check: false

demo:
  service:
    version: 1.0.0