# Spring boot application
spring:
  application:
    name: springboot-consumer
#  redis:
#    database: 0
#    host: localhost
#    port: 6379
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 8
#        min-idle: 0
#    timeout: 0

server:
  port: 8080
management:
  prot: 8081

## nacos
nacos:
  config:
    server-addr: 47.106.227.5:8848
  discovery:
    server-addr: 47.106.227.5:8848

## application
dubbo:
  application:
    id: dubbo-consumer
    name: dubbo-consumer
    qos-port: 33333
## nacos registry address
  registry:
    id: my-registry
    address: nacos://47.106.227.5:8848
  protocol:
    id: dubbo
    name: dubbo
    port: -1
#  scan:
#    basePackages: com.ghost.springboot.service
  consumer:
    check: false

demo:
  service:
    version: 1.0.0